server:
  port: 8083
spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/complex
    username: postgres
    password: db#ncfans@vae
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always